#!/bin/sh

mtdpart="firmware"

workdir="/var/run/mount_firmware"
statefile="${workdir}/state"
dumpfile="${workdir}/${mtdpart}.bin"

workromdir="${workdir}/rom"
workoverlaydir="${workdir}/overlay"

overlayfsdir="/${mtdpart}"
romdir="${overlayfsdir}/rom"
overlaydir="${overlayfsdir}/overlay"

function main() {
	if [[ ! -e "${statefile}" ]]; then
		echo "Firmware not mounted"
		exit 1
	fi

	echo "Loading mount state..."
	source ${statefile}

	echo "Unmounting overlay filesystem..."
	umount ${romdir} && umount ${overlaydir} && umount ${overlayfsdir}
	if [[ "$?" == "1" ]]; then
		echo "Could not unmount overlay filesystem"
		exit 1
	fi

	echo "Unmounting rootfs and rootfs_data..."
	umount ${workromdir} && umount ${workoverlaydir}
	if [[ "$?" == "1" ]]; then
		echo "Could not unmount rootfs and rootfs_data"
		exit 1
	fi

	echo "Flushing buffers..."
	sync

	echo "Removing auxiliary mtdblock device partitions..."
	rmmod block2mtd
	if [[ "$?" == "1" ]]; then
		echo "Could not remove auxiliary mtdblock device partitions"
		exit 1
	fi

	echo "Removing rootfs and rootfs_data loop devices..."
	losetup -d ${rootfs} ${rootfs_data}
	if [[ "$?" == "1" ]]; then
		echo "Could not remove rootfs and rootfs_data loop devices"
		exit 1
	fi

	while true; do
		read -p "Do you want to write changes to flash? [yn] " yn
		case $yn in
			[Yy]*)
				echo "Writing changes to flash..."
				mtd -q -q write ${dumpfile} ${mtdpart}
				break
				;;
			[Nn]*)
				break
				;;
		esac
	done

	echo "Cleaning up any leftover files..."
	rmdir ${overlayfsdir}
	rm -rf ${workdir}

	echo "${mtdpart} was successfully unmounted from ${overlayfsdir}"
}

main